### ISSUE TITLE
DSN gets data for Procyon on April 3rd, change its DSN name after that

### ISSUE THREAD

**Issue by basilleaf** [basilleaf/spaceprobes#30]
https://github.com/basilleaf/spaceprobes/blob/master/probes/_posts/2014-12-03-procyon.markdown

**Comment by ariel** [comment]
It actually pulls it on April 5th. So was thinking of changing it on April 3rd to make sure it'd be pulling the data in time?

**Comment by basilleaf** [comment]
looks like we got it already so can be updated whenever. This is what we have and it's there: http://murmuring-anchorage-8062.herokuapp.com/dsn/probes.json PRCN

**Comment by ariel** [comment]
Deployed with PRCN name. Closing issue.

**Comment by basilleaf** [comment]
right on. btw just fyi if you say "fixes #30" (or whatever issue #) in your commit message it will close automatically
